import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
import anthropic
from tavily import TavilyClient

# Load our secret keys
load_dotenv()

# Set up our two tools
claude = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))

# Companies to track every day
TRACKED_COMPANIES = [
    "Anthropic",
    "OpenAI",
    "Google DeepMind",
    "Meta AI"
]

def search_web(query):
    """Tool: Search the web using Tavily"""
    print(f"  🔍 Searching: {query}")
    results = tavily.search(query=query, max_results=5)
    return results["results"]

def format_results(search_results):
    """Format search results for Claude to read"""
    formatted = ""
    for i, result in enumerate(search_results, 1):
        formatted += f"\nSource {i}: {result['title']}\n"
        formatted += f"URL: {result['url']}\n"
        formatted += f"Content: {result['content']}\n"
        formatted += "-" * 50
    return formatted

def generate_html(digest_text, today):
    """Convert the digest into a beautiful HTML page"""
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI News Digest — {today}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont,
                         'Segoe UI', sans-serif;
            background: #0f0f13;
            color: #e0e0e0;
            line-height: 1.7;
            padding: 40px 20px;
        }}

        .container {{
            max-width: 800px;
            margin: 0 auto;
        }}

        .header {{
            text-align: center;
            padding: 40px;
            background: linear-gradient(135deg, #1a1a2e, #16213e);
            border-radius: 20px;
            margin-bottom: 30px;
            border: 1px solid #2a2a4a;
        }}

        .header h1 {{
            font-size: 2em;
            color: #7c83ff;
            margin-bottom: 8px;
        }}

        .header .date {{
            color: #888;
            font-size: 1em;
        }}

        .card {{
            background: #1a1a2e;
            border-radius: 16px;
            padding: 28px;
            margin-bottom: 20px;
            border: 1px solid #2a2a4a;
            transition: transform 0.2s;
        }}

        .card:hover {{
            transform: translateY(-2px);
        }}

        .card h2 {{
            font-size: 1.2em;
            color: #7c83ff;
            margin-bottom: 16px;
            padding-bottom: 10px;
            border-bottom: 1px solid #2a2a4a;
        }}

        .story-title {{
            color: #ffffff;
            font-weight: 600;
            font-size: 1em;
            margin: 16px 0 6px 0;
        }}

        .story-title:first-child {{
            margin-top: 0;
        }}

        ul {{
            padding-left: 20px;
        }}

        ul li {{
            margin-bottom: 8px;
            color: #b0b0c0;
        }}

        .company-grid {{
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px;
            margin-top: 8px;
        }}

        .company-card {{
            background: #0f0f1a;
            border-radius: 10px;
            padding: 14px;
            border: 1px solid #2a2a4a;
        }}

        .company-name {{
            color: #7c83ff;
            font-weight: 600;
            margin-bottom: 6px;
        }}

        .highlight {{
            background: linear-gradient(135deg, #1e1e3a, #1a2a3a);
            border-left: 4px solid #7c83ff;
        }}

        .big-picture {{
            background: linear-gradient(135deg, #1a2a1a, #1a1a2e);
            border-left: 4px solid #4caf50;
        }}

        .india {{
            border-left: 4px solid #ff9933;
        }}

        .footer {{
            text-align: center;
            color: #444;
            font-size: 0.85em;
            margin-top: 40px;
            padding: 20px;
        }}

        p {{
            color: #b0b0c0;
            margin-bottom: 10px;
        }}
    </style>
</head>
<body>
    <div class="container">

        <div class="header">
            <h1>🤖 AI News Digest</h1>
            <div class="date">📅 {today}</div>
        </div>

        <div class="card">
            <pre style="white-space: pre-wrap;
                        font-family: inherit;
                        color: #b0b0c0;
                        font-size: 0.95em;">
{digest_text}
            </pre>
        </div>

        <div class="footer">
            Generated by AI News Agent • {today}<br>
            Powered by Claude + Tavily
        </div>

    </div>
</body>
</html>
"""
    return html

def send_email(html_content, digest_text, today):
    """Send the digest to your email"""
    sender = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("EMAIL_PASSWORD")
    recipient = os.getenv("EMAIL_RECIPIENT")

    if not all([sender, password, recipient]):
        print("  ⚠️  Email not configured — skipping")
        return

    print("\n📧 PHASE 5: Sending email...")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🤖 AI News Digest — {today}"
    msg["From"] = sender
    msg["To"] = recipient

    text_part = MIMEText(digest_text, "plain")
    html_part = MIMEText(html_content, "html")

    msg.attach(text_part)
    msg.attach(html_part)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        print(f"  ✅ Email sent to {recipient}")
    except Exception as e:
        print(f"  ❌ Email failed: {e}")

def push_to_github():
    """Automatically push latest report to GitHub"""
    print("\n🐙 PHASE 4: Pushing to GitHub...")
    os.system("cp AI_News_*.html index.html")
    os.system("git add index.html netlify.toml")
    os.system(f'git commit -m "AI News Digest — {date.today()}"')
    os.system("git push origin main")
    print("  ✅ Pushed to GitHub!")

def run_agent():
    """The main agent loop"""
    today = date.today().strftime("%B %d, %Y")

    print("\n" + "=" * 60)
    print("🤖 AI NEWS AGENT")
    print(f"📅 {today}")
    print("=" * 60)

    # Phase 1: Search all topics
    print("\n📡 PHASE 1: Collecting news...\n")

    searches = [
        "AI research breakthroughs this week 2026",
        "new AI products and tools launched this week",
        "AI in healthcare news this week",
        "AI regulation and policy news this week",
        "AI industry business deals funding this week",
        "India AI news this week 2026",
        "India AI startups funding this week",
        "India government AI policy this week"
    ]

    # Company specific searches
    for company in TRACKED_COMPANIES:
        searches.append(f"{company} latest news this week 2026")

    all_results = []
    for query in searches:
        results = search_web(query)
        all_results.extend(results)

    print(f"\n✅ Collected {len(all_results)} articles")

    # Phase 2: Claude analyses everything
    print("\n🧠 PHASE 2: Claude is analysing...\n")

    formatted_results = format_results(all_results)
    companies_list = ", ".join(TRACKED_COMPANIES)

    response = claude.messages.create(
        model="claude-opus-4-5",
        max_tokens=4000,
        messages=[
            {
                "role": "user",
                "content": f"""You are an expert AI industry analyst
creating a professional daily briefing.

Today is {today}.

Here are today's AI news articles:

{formatted_results}

Create a professional AI News Digest with
EXACTLY this structure:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🤖 AI NEWS DIGEST — {today}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 TODAY AT A GLANCE
[3 bullet points — the 3 most important
things that happened today in AI globally
and in India]

🔬 RESEARCH & BREAKTHROUGHS
[2 most significant research stories
Each with: Title, 2-3 sentence summary,
Why it matters]

🚀 NEW PRODUCTS & TOOLS
[2 most interesting product launches
Each with: Title, 2-3 sentence summary,
Who should care about this]

🏥 AI IN HEALTHCARE
[1-2 healthcare specific AI stories
Each with: Title, 2-3 sentence summary,
Impact on the industry]

💼 BUSINESS & FUNDING
[1-2 business/funding stories
Each with: Title, 2-3 sentence summary,
What this signals]

⚖️ POLICY & REGULATION
[1 policy story if available
Title, 2-3 sentence summary,
Why this matters long term]

🇮🇳 AI IN INDIA
[2 India specific AI stories
Each with: Title, 2-3 sentence summary,
What this means for India's AI journey]

🏢 COMPANY TRACKER — {companies_list}
[For EACH of these 4 companies write:
Company name, one key update this week,
one sentence on what it signals.
If no news found write "Quiet week"]

🌟 STORY OF THE DAY
[The single most important or
interesting story — explained simply]

💡 BIG PICTURE
[One paragraph: Overall theme of AI
this week — global and India perspective]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Write clearly. Be specific. No fluff.
Make it genuinely useful to read."""
            }
        ]
    )

    digest = response.content[0].text

    # Phase 3: Save files
    print("\n💾 PHASE 3: Saving files...\n")

    filename_base = f"AI_News_{date.today().strftime('%Y_%m_%d')}"

    # Save .txt
    txt_file = f"{filename_base}.txt"
    with open(txt_file, "w", encoding="utf-8") as f:
        f.write(digest)
        f.write(f"\n\n---\nGenerated by AI News Agent on {today}")
    print(f"  ✅ Saved: {txt_file}")

    # Save .html
    html_content = generate_html(digest, today)
    html_file = f"{filename_base}.html"
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"  ✅ Saved: {html_file}")

    # Auto open in browser
    os.system(f"open {html_file}")
    print(f"  🌐 Opened in browser!")

    # Phase 4: Push to GitHub
    push_to_github()

    # Phase 5: Send email (skipped if not configured)
    send_email(html_content, digest, today)

    # Print to terminal
    print("\n" + "=" * 60)
    print(digest)
    print("=" * 60)

    print("\n✅ Agent complete!\n")

# Run the agent
if __name__ == "__main__":
    run_agent()